/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BranchChatDto { 
    /**
     * Number of raw messages (from the start of the rolling messages[] array) to carry over into the branched chat
     */
    keepMessageCount: number;
}

