/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EphemeralMcpIntegrationDto } from './ephemeralMcpIntegrationDto';
import { GeneratedAssetDto } from './generatedAssetDto';


export interface ChatMetadataDto { 
    /**
     * MongoDB ObjectId — use as chatInternalId when fetching messages
     */
    _id: string;
    name: string;
    client: ChatMetadataDto.ClientEnum;
    usedModel: string;
    /**
     * ObjectId of the owning user
     */
    userId: string;
    reasoningMode: string;
    tools?: Array<EphemeralMcpIntegrationDto>;
    createdAt: string;
    updatedAt: string;
    useCrypto?: boolean;
    cryptoKey?: string;
    openAiEndpointPreference?: ChatMetadataDto.OpenAiEndpointPreferenceEnum;
    generatedAssets?: Array<GeneratedAssetDto>;
    userAssets?: Array<GeneratedAssetDto>;
    lastMessageSentAt: string;
    useInvoke?: boolean;
    invokeAiModelToUse?: ChatMetadataDto.InvokeAiModelToUseEnum;
    /**
     * ObjectIds of users granted access to this chat
     */
    sharedWith?: Array<string>;
    /**
     * Usernames of users in sharedWith, same order/index — resolved server-side
     */
    sharedWithUsernames?: Array<string>;
    /**
     * True while a prompt is currently streaming for this chat
     */
    locked?: boolean;
}
export namespace ChatMetadataDto {
    export const ClientEnum = {
        Openai: 'OPENAI',
        Lmstudio: 'LMSTUDIO'
    } as const;
    export type ClientEnum = typeof ClientEnum[keyof typeof ClientEnum];
    export const OpenAiEndpointPreferenceEnum = {
        Responses: 'RESPONSES',
        Completion: 'COMPLETION'
    } as const;
    export type OpenAiEndpointPreferenceEnum = typeof OpenAiEndpointPreferenceEnum[keyof typeof OpenAiEndpointPreferenceEnum];
    export const InvokeAiModelToUseEnum = {
        Dreamshaper8: 'Dreamshaper 8',
        JuggernautXlV9: 'Juggernaut XL v9'
    } as const;
    export type InvokeAiModelToUseEnum = typeof InvokeAiModelToUseEnum[keyof typeof InvokeAiModelToUseEnum];
}


