/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatMcpOverrideDto } from './chatMcpOverrideDto';
import { EphemeralMcpIntegrationDto } from './ephemeralMcpIntegrationDto';


export interface CreateChatMetadataDto { 
    /**
     * Human-readable name for this chat session
     */
    name: string;
    /**
     * LLM model identifier used in this session
     */
    usedModel: string;
    client: CreateChatMetadataDto.ClientEnum;
    /**
     * Reasoning mode (e.g. off / low / medium / high / on)
     */
    reasoningMode: string;
    /**
     * MCP integrations to associate with this session
     */
    tools?: Array<EphemeralMcpIntegrationDto>;
    useCrypto?: boolean;
    cryptoKey?: string;
    openAiEndpointPreference?: CreateChatMetadataDto.OpenAiEndpointPreferenceEnum;
    useInvoke?: boolean;
    invokeAiModelToUse?: CreateChatMetadataDto.InvokeAiModelToUseEnum;
    transcribeAudio?: boolean;
    toolsRequireApproval?: boolean;
    lastMessageSentAt?: string;
    /**
     * Opt-out overrides for the user\'s account-level custom MCP servers
     */
    mcpOverrides?: Array<ChatMcpOverrideDto>;
}
export namespace CreateChatMetadataDto {
    export const ClientEnum = {
        Openai: 'OPENAI',
        Lmstudio: 'LMSTUDIO'
    } as const;
    export type ClientEnum = typeof ClientEnum[keyof typeof ClientEnum];
    export const OpenAiEndpointPreferenceEnum = {
        Responses: 'RESPONSES',
        Completion: 'COMPLETION'
    } as const;
    export type OpenAiEndpointPreferenceEnum = typeof OpenAiEndpointPreferenceEnum[keyof typeof OpenAiEndpointPreferenceEnum];
    export const InvokeAiModelToUseEnum = {
        Dreamshaper8: 'Dreamshaper 8',
        JuggernautXlV9: 'Juggernaut XL v9'
    } as const;
    export type InvokeAiModelToUseEnum = typeof InvokeAiModelToUseEnum[keyof typeof InvokeAiModelToUseEnum];
}


