/**
 * LMStudio Wrapper API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateAndAddToUserAssetsResponseDto {
  /**
   * Asset size in KB
   */
  sizeKb: number;
  /**
   * URL to asset
   */
  assetUrl: string;
  /**
   * Filename
   */
  filename: string;

  internalFilename: string;
}

