/**
 * LMStudio Wrapper API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GeneratedAssetDto {
    _id: string;
    filename: string;
    refId: string;
    type: GeneratedAssetDto.TypeEnum;
    url: string;
    thumbnail?: string;
    sizeKb?: number;
    isVisible: boolean;
    mimeType?: string;
}
export namespace GeneratedAssetDto {
    export const TypeEnum = {
        Image: 'IMAGE',
        File: 'FILE'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


