/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CustomMcpDto } from './customMcpDto';


export interface MeDto {
    username: string;
    role: string;
    subscription: string;
    isActivated: boolean;
    usedTokens: number;
    tokenCountResetDate: string;
    tokenLimit: number;
    customMcps: Array<CustomMcpDto>;
}

