/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResolveToolApprovalDto { 
    decision: ResolveToolApprovalDto.DecisionEnum;
}
export namespace ResolveToolApprovalDto {
    export const DecisionEnum = {
        Approve: 'approve',
        Deny: 'deny',
        Always: 'always'
    } as const;
    export type DecisionEnum = typeof DecisionEnum[keyof typeof DecisionEnum];
}


