/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatMcpOverrideDto } from './chatMcpOverrideDto';
import { EphemeralMcpIntegrationDto } from './ephemeralMcpIntegrationDto';


export interface UpdateChatMetadataDto { 
    name?: string;
    usedModel?: string;
    reasoningMode?: string;
    tools?: Array<EphemeralMcpIntegrationDto>;
    lastMessageSentAt?: string;
    useCrypto?: boolean;
    cryptoKey?: string;
    openAiEndpointPreference?: UpdateChatMetadataDto.OpenAiEndpointPreferenceEnum;
    useInvoke?: boolean;
    invokeAiModelToUse?: UpdateChatMetadataDto.InvokeAiModelToUseEnum;
    transcribeAudio?: boolean;
    toolsRequireApproval?: boolean;
    /**
     * Opt-out overrides for the user\'s account-level custom MCP servers
     */
    mcpOverrides?: Array<ChatMcpOverrideDto>;
}
export namespace UpdateChatMetadataDto {
    export const OpenAiEndpointPreferenceEnum = {
        Responses: 'RESPONSES',
        Completion: 'COMPLETION'
    } as const;
    export type OpenAiEndpointPreferenceEnum = typeof OpenAiEndpointPreferenceEnum[keyof typeof OpenAiEndpointPreferenceEnum];
    export const InvokeAiModelToUseEnum = {
        Dreamshaper8: 'Dreamshaper 8',
        JuggernautXlV9: 'Juggernaut XL v9'
    } as const;
    export type InvokeAiModelToUseEnum = typeof InvokeAiModelToUseEnum[keyof typeof InvokeAiModelToUseEnum];
}


